version: "3"

services: 

  postgres:
    image: postgres:10.0-alpine
    container_name: db-postgres
    ports: 
      - "5432:5432" 
    restart: always
    networks: 
      - backend
       
  app:
    build: .
    container_name: mybooks-server
    ports:
      - "3333:3333"
    volumes: 
      - .:/usr/app
    command: yarn prod
    restart: always
    networks: 
      - backend
                   
networks:
  backend:
    driver: bridge
    